// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ediuakbfvfbkuigvguge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkaXVha2JmdmZia3VpZ3ZndWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzEwNDMsImV4cCI6MjA2NDI0NzA0M30.-LAlZdjX2K70_aK9X12cdyuI9Y9_xzrk-Z7oqltPjgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);